### ISSUE TITLE
How to use Meteor Methods

### ISSUE THREAD

**Issue by tlianza** [meteor-typescript/meteor-typescript-libs#10]
I'm wondering if it's possible to use [Meteor methods](http://docs.meteor.com/#/full/meteor_methods) in TypeScript?  An example would be fantastic.  I'm having trouble calling them since "Meteor.call" is defined as a method that returns void. And, in my app I have Meteor methods that return various objects.

**Comment by fullflavedave** [comment]
This is a bug.  I'll fix the definitions so that "Meteor.call()" and "Meteor.apply()" both return type "any".

**Comment by fullflavedave** [comment]
Closing since this is now fixed in version 1.0.13 on atmosphere.
