### ISSUE TITLE
Missing definition files referenced from all-definitions.d.ts

### ISSUE THREAD

**Issue by tlianza** [meteor-typescript/meteor-typescript-libs#12]
collection2.d.ts, simple-schema.d.ts, and json-schema.d.ts don't seem to be in master.

https://github.com/meteor-typescript/meteor-typescript-libs/commit/3479f76cd3fa0d841fb2c109250e94af5ea1decb#commitcomment-10289950

**Comment by fullflavedave** [comment]
Woops -- I'll fix this tomorrow.
