### ISSUE TITLE
Errors in file mongodb.d.ts

### ISSUE THREAD

**Issue by kabala** [meteor-typescript/meteor-typescript-libs#14]
Hi guys,

I think all this file is wrong because it has a html5 markup and when i run my app it gives me this error.

/home/carlos/Documentos/metor_collections/lib/definitions/mongodb.d.ts:5:2: error TS1110: Type expected.

Please can you help me??

**Comment by fullflavedave** [comment]
Sorry about that.  The mongo.d.ts file was leftover from an experiment in including those definitions, and I never worked out all the issues.  I just removed that file from.
