### ISSUE TITLE
Mongo.Collection.insert()

### ISSUE THREAD

**Issue by arturadib** [meteor-typescript/meteor-typescript-libs#15]
Wondering if the argument of `Mongo.Collection.insert` should match the generic type? I.e. in `meteor.d.ts` line 585, instead of:

```javascript
  insert(doc: Object, callback?: Function): string;
```

do

```javascript
  insert(doc: T, callback?: Function): string;
```

so that we get the proper type-checking when inserting a document?

**Comment by fullflavedave** [comment]
Good catch.  I’ll fix this on Monday.
