### ISSUE TITLE
Can't get EJSON.addType to work

### ISSUE THREAD

**Issue by vjau** [meteor-typescript/meteor-typescript-libs#16]
Hi, i have trouble to get EJSON.addType to work, the compiler always complains about the factory provided. Anyone has pointers to help me do this ?
Additionnaly, the definition says this :
```js
function addType(name: string, factory: (val: EJSONable) => JSONable): void;
```

Should'nt it be the opposite ? 
```js
function addType(name: string, factory: (val: JSONable) => EJSONable): void;
```
, since the factory is taking a valid JSON string and create ("revive") the custom type ? 

Thank you in advance.

**Comment by vjau** [comment]
Actually, shouldn't it be :
```js
function addType(name: string, factory: (val: JSON) => EJSONable): void;
```
?

**Comment by fullflavedave** [comment]
Thanks for finding this -- it should be fixed now.

**Comment by vjau** [comment]
Sorry, after having read and re-read the (unclear) documentation and after many experimentations, i think the correct line is this:
```js
function addType(name: string, factory: (val: JSONable) => EJSON.CustomType): void;
```

Other input would be appreciated.
