### ISSUE TITLE
TomiUploads.d.ts doesn't compile in its current form

### ISSUE THREAD

**Issue by SebastianKG** [meteor-typescript/meteor-typescript-libs#23]
TomiUploads.d.ts doesn't compile in its current form, running on Windows 7 and Meteor 1.1.0.2.
 
```
While building the application:
   C:\Users\user\Documents\abcdef\zzz.ts-compiler.ts:
   C:/Users/user/Documents/abcdef/definitions/tomiUploads.d.ts(11,13): error TS2403: Subsequent variable
   declarations must have the same type.  Variable 'process' must be of type 'Process', but here has type
   'any'.
```

**Comment by fullflavedave** [comment]
@tomitrescak -- in tomiUploads.d.ts, there is a `declare var process : any;` that can conflict with the `declare var process: NodeJS.Process;` in node.d.ts.  Is this `process` the same one as in node.d.ts, and if so, can we give it the same type (or remove it and just use the typing for process in node.d.ts)?
