### ISSUE TITLE
(Suggestion) separate into meteor.client.d.ts & meteor.server.d.ts & meteor.common.d.ts  

### ISSUE THREAD

**Issue by D1no** [meteor-typescript/meteor-typescript-libs#25]
Currently the meteor.d.ts has both client and server side interfaces. While going down on https://github.com/meteor-typescript/meteor-typescript-libs/issues/24 in creating a quick interface for "Plugin" of the new Build API, I ran into conflicts with the default lib (lib.dom.d.ts) in TypeScript that types "Plugin" as an ES2015 feature (generator) of the Browser. Though there is no browser on the server, I needed to pull apart the default TypeScript lib to be able to re reasign the generator. 

Following that, I found a few more server-client conflicts with third-party frameworks that also declare i.e. Npm or Package as meteor does on the server side.

To slim down linting and potential conflicts in the respective folders for client vs server side code, it would be great if we could separate the client and server declarations into 
- meteor.common
- meteor.client
- meteor.server

that are potentially referenced into meteor.d.ts. Just for our global variables.

**Comment by fullflavedave** [comment]
I’ll take a look at this and #24 next week when I return to the office.

**Comment by fullflavedave** [comment]
This seems like a reasonable request since that, in the data.js definitions file, each definition contains a "locus" field that specifies "Anywhere", "Client", or "Server".  I'll give this an initial stab today, but it won't be until at least next week that I finish.

**Comment by D1no** [comment]
That sounds great, especially since meteor 1.2 is finally in RC.

I am currently testing and writing an "integrated" typescript compiler based on the new plugins API which could make inherent use of the separated declarations. 🎉

**Comment by fullflavedave** [comment]
@D1no:  I created a new branch with 5 new meteor definitions files:
- meteor.common.d.ts
- meteor.client.d.ts
- meteor.server.d.ts
- meteor.package.d.ts
- meteor.build.d.ts

The branch is split_meteor_defs (https://github.com/meteor-typescript/meteor-typescript-libs/tree/split_meteor_defs).  Please let me know if the latest from that branch works for what you are doing.

**Comment by fullflavedave** [comment]
@D1no:  Note that if no methods/members of a module or interface are available for common, client, or server, the definitions for that locus still contain the module or interface declaration, but as an empty shell with no methods/members inside.  I didn't yet change the generator code to traverse down the json tree first to determine whether to even declare the module or interface.
