### ISSUE TITLE
Clarification about splitting of the definitions files

### ISSUE THREAD

**Issue by vjau** [meteor-typescript/meteor-typescript-libs#33]
Hi everyone,
as far as i understand it, defintions files have been splitted into common/client/server/packages... but there is still a meteor.d.ts file that is the aggregate of all separated files for those that are not interested in having separated files. Am i correct ?

Now, what's the point of the meteor-manually-maintained-definitions.d.ts file, since those seems also to be splitted ?

Thank you.

**Comment by fullflavedave** [comment]
Good catch.  meteor-manually-maintained-definitions.d.ts is now irrelevant.  I'll delete it.
