### ISSUE TITLE
Typing of Meteor.settings

### ISSUE THREAD

**Issue by horyd** [meteor-typescript/meteor-typescript-libs#41]
Is there an explicit reason for this typing on Meteor.settings?

```
var settings: {[id:string]: any};
```

I realise that the standard is to write the settings.json file with keys in quotations, but when using the object in code it's a little weird. Using ```Meteor.settings.public.sentry.dsn``` works fine, but the TypeScript wants to always see ```Meteor.settings["public"].sentry.dsn```. It then can get confusing if you also have private settings in the main object as ```Meteor.settings.sentry.dsn```, which it wants to see as ```Meteor.settings["sentry"].dsn``` (if not using the "private" key which is available but not entirely necessary)

I'm a bit of a TypeScript beginner so correct me if my thinking is down the wrong track :)

**Comment by fullflavedave** [comment]
Unless something has changed recently, my understanding is that TypeScript code won't compile if you try to use dot notation for unknown keys/objects (e.g. Meteor.settings, where the keys could be anything).  However, code will compile using bracket notation for unknown keys/objects.

This definition for Meteor.settings was written before union types were available, and I couldn't figure out a way to specify both that there exists a "public" key, and that there could be any other key, so the most flexible and inclusive definition was `{[id:string]: any};`.

Now that union types have been introduced, a better definition may be possible.  I'll have to play with it.  However, although this definition seems correct:

        var settings: { public: {[id:string]: any}} | {[id:string]: any};

my compiler still complains when I try to type `Meteor.settings.public['someKey']` using this definition.

I'll have time to fool with this and update all of the definitions after the holidays, but if you can come up with a better definition, please post it here.

**Comment by horyd** [comment]
Ok I did some reading and see what you mean about the dot notation. I tried this in the playground with good results, let me know what you think.

var settings: { public: {[id:string]: any}, private: {[id:string]: any}, [id:string]: any};

**Comment by fullflavedave** [comment]
Sorry for the delay -- holiday/vacation laziness.

Your code worked great for me, and I'll update the next release with it.  Thanks for your contribution!

**Comment by horyd** [comment]
No worries, happy to contribute :+1: :)
