### ISSUE TITLE
How to use this in 0.9.0+ ?

### ISSUE THREAD

**Issue by tomitrescak** [meteor-typescript/meteor-typescript-libs#6]
Hi

Since meteor 0.9.0 files are no longer located in the "packages" folder and are hidden away from the user. How do I set up paths in in reference paths?

You mention: `///<reference path="/path/to/packages/typescript-libs/all-definitions.d.ts" />`

But do you really mean something like this?

`///<reference path="~/.meteor/packages/orefalo/typescript-libs" />` Yet I even checked there and nothing is in there except 0-sized js files.

**Comment by fullflavedave** [comment]
The package has been updated multiple times since this issue was opened, and new docs should explain how to reference the definitions:  https://atmospherejs.com/meteortypescript/typescript-libs.  Closing this issue.
